os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL swift.qutheory.io/07-20)"
script:
  # Build Core
  - swift build
  - swift build --configuration release
  # Test Core
  - swift test
